name: ETL Backup Diário

# Agenda para rodar todo dia às 02:00 da manhã (UTC)
on:
  push:
    branches:
      - workflows
  workflow_dispatch: # permite rodar manualmente

jobs:
  run-etl:
    runs-on: ubuntu-latest
    env:
      BANCO_INICIAL: ${{ secrets.BANCO_INICIAL }}
      BANCO_BACKUP: ${{ secrets.BANCO_BACKUP }}
      MONGO_DB_NAME_INICIAL: ${{ secrets.MONGO_DB_NAME_INICIAL }}
      MONGO_COLLECTION_MEMBRO_INICIAL: ${{ secrets.MONGO_COLLECTION_MEMBRO_INICIAL }}
      MONGO_DB_BACKUP: ${{ secrets.MONGO_DB_BACKUP }}
      MONGO_COLLECTION_BACKUP: ${{ secrets.MONGO_COLLECTION_BACKUP }}

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Build e rodar container ETL
        id: run_docker
        run: |
          docker build -t etl-backup .
          # Executa o container e captura o log em uma variável
          docker run --rm \
            -e BANCO_INICIAL \
            -e BANCO_BACKUP \
            -e MONGO_DB_NAME_INICIAL \
            -e MONGO_COLLECTION_MEMBRO_INICIAL \
            -e MONGO_DB_BACKUP \
            -e MONGO_COLLECTION_BACKUP \
            etl-backup | tee docker_output.log
          echo "LOG_CONTENT<<EOF" >> $GITHUB_ENV
          cat docker_output.log >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Enviar e-mail de notificação
        if: always()  # roda mesmo se o job falhar
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASS }}
          subject: "ETL Backup Diário - ${{ job.status }}"
          body: ${{ env.LOG_CONTENT }}
          to: seuemail@dominio.com
          from: ${{ secrets.SMTP_USER }}
