name: ETL Backup Diário

# Agenda para rodar todo dia às 02:00 da manhã (UTC)
on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch: # permite rodar manualmente

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Build e rodar container ETL
        run: |
          docker build -t etl-backup .
          docker run --rm \
            -e BANCO_INICIAL="${{ secrets.BANCO_INICIAL }}" \
            -e BANCO_BACKUP="${{ secrets.BANCO_BACKUP }}" \
            -e MONGO_DB_NAME_INICIAL="${{ secrets.MONGO_DB_NAME_INICIAL }}" \
            -e MONGO_COLLECTION_MEMBRO_INICIAL="${{ secrets.MONGO_COLLECTION_MEMBRO_INICIAL }}" \
            -e MONGO_DB_BACKUP="${{ secrets.MONGO_DB_BACKUP }}" \
            -e MONGO_COLLECTION_BACKUP="${{ secrets.MONGO_COLLECTION_BACKUP }}" \
            etl-backup
